[build]
  base = "dashboard"
  publish = ".next"
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_USE_NETLIFY_EDGE = "true"
  NEXT_PUBLIC_SUPABASE_URL = "https://ihuxlbfqevubzsqebszp.supabase.co"
